function mulberry32(a){return function(){let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
const speciesPresets=[{id:'grazer',name:'草食敏捷体',role:'资源采食 / 快速繁殖',color:'#9df2b1',traits:{speed:62,camouflage:38,fertility:76,metabolism:58,resistance:42,aggression:18}},{id:'predator',name:'中型捕食体',role:'捕猎压制 / 低繁殖',color:'#ffb37c',traits:{speed:70,camouflage:34,fertility:32,metabolism:72,resistance:55,aggression:84}},{id:'scavenger',name:'杂食机会体',role:'环境波动适应 / 泛化生存',color:'#7cc8ff',traits:{speed:48,camouflage:44,fertility:58,metabolism:46,resistance:60,aggression:36}},{id:'parasite',name:'寄生微型体',role:'高扩散 / 高环境依赖',color:'#d7a9ff',traits:{speed:26,camouflage:68,fertility:82,metabolism:40,resistance:30,aggression:22}}]
export function getSpeciesPresets(){return speciesPresets}
export function createInitialWorld({seed,climateMode}){const random=mulberry32(seed);const climateLabelMap={temperate:'温和',drought:'干旱',cold:'寒冷',volatile:'剧烈波动'};const world={seed,random,tick:0,environment:{climateMode,climateLabel:climateLabelMap[climateMode],temperature:climateMode==='cold'?20:climateMode==='drought'?78:52,humidity:climateMode==='drought'?22:climateMode==='cold'?46:61,resources:climateMode==='drought'?56:100,hazard:12},species:speciesPresets.map((preset,index)=>({...JSON.parse(JSON.stringify(preset)),population:80-index*8,x:120+index*180,y:160+index*70})),history:[]};recordHistory(world);return world}
function clamp(num,min,max){return Math.max(min,Math.min(max,num))}
function mutateTrait(value,delta){return clamp(value+delta,1,99)}
function recordHistory(world){world.history.push({tick:world.tick,species:world.species.map(s=>({id:s.id,name:s.name,population:s.population,color:s.color}))});if(world.history.length>80)world.history.shift()}
function updateEnvironment(world){const r=world.random();const env=world.environment;if(env.climateMode==='volatile'){env.temperature=clamp(env.temperature+(r-.5)*28,5,95);env.humidity=clamp(env.humidity+(world.random()-.5)*32,5,95)}else if(env.climateMode==='drought'){env.temperature=clamp(env.temperature+(r-.3)*8,40,95);env.humidity=clamp(env.humidity+(world.random()-.7)*8,5,40)}else if(env.climateMode==='cold'){env.temperature=clamp(env.temperature+(r-.7)*10,0,42);env.humidity=clamp(env.humidity+(world.random()-.4)*10,20,70)}else{env.temperature=clamp(env.temperature+(r-.5)*8,20,80);env.humidity=clamp(env.humidity+(world.random()-.5)*10,20,80)}env.resources=clamp(env.resources+(env.humidity/18)-(env.temperature/35)-(env.hazard/25)+(world.random()-.5)*4,10,140);env.hazard=clamp(env.hazard+(world.random()-.48)*8+(env.climateMode==='volatile'?2:0),5,40);return `Tick ${world.tick}: 气温 ${env.temperature.toFixed(0)}，湿度 ${env.humidity.toFixed(0)}，资源 ${env.resources.toFixed(0)}，风险 ${env.hazard.toFixed(0)}`}
function applyStrategies(world,strategyProvider){const narratives=[];for(const species of world.species){const strategy=strategyProvider.getStrategy({world,species});species.traits.speed=mutateTrait(species.traits.speed,strategy.mutationBias.speed);species.traits.camouflage=mutateTrait(species.traits.camouflage,strategy.mutationBias.camouflage);species.traits.fertility=mutateTrait(species.traits.fertility,strategy.mutationBias.fertility);species.traits.metabolism=mutateTrait(species.traits.metabolism,strategy.mutationBias.metabolism);species.traits.resistance=mutateTrait(species.traits.resistance,strategy.mutationBias.resistance);species.traits.aggression=mutateTrait(species.traits.aggression,strategy.mutationBias.aggression);narratives.push(`${species.name}：${strategy.narrative}`)}return narratives}
function resolvePopulation(world){const env=world.environment;const predatorPressure=world.species.find(s=>s.id==='predator')?.population||0;for(const species of world.species){const t=species.traits;const resourceGain=env.resources*(.004+t.metabolism/4000);const fertilityGain=t.fertility/22;const temperatureStress=Math.abs(env.temperature-50)/10;const droughtStress=env.humidity<25?(70-t.resistance)/26:0;const hazardStress=env.hazard/8-t.resistance/26;const predationStress=species.id==='predator'?0:predatorPressure/120-(t.speed+t.camouflage)/160;const delta=resourceGain+fertilityGain-temperatureStress-droughtStress-hazardStress-predationStress;species.population=clamp(Math.round(species.population+delta),0,240);species.x=clamp(species.x+(world.random()-.5)*24+(t.speed-50)*.08,40,860);species.y=clamp(species.y+(world.random()-.5)*24+(t.camouflage-50)*.05,40,480)} }
export function stepWorld(world,strategyProvider){world.tick+=1;const environmentNarrative=updateEnvironment(world);const speciesNarratives=applyStrategies(world,strategyProvider);resolvePopulation(world);recordHistory(world);return {environmentNarrative,speciesNarratives}}