function mulberry32(a){return function(){let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}

const speciesPresets=[
  {id:'microbe',name:'原初微生体',tier:0,role:'低级生命 / 环境塑造',color:'#b7ffd8',traits:{speed:18,camouflage:72,fertility:92,metabolism:18,resistance:64,aggression:4}},
  {id:'grazer',name:'草食敏捷体',tier:2,role:'资源采食 / 快速繁殖',color:'#9df2b1',traits:{speed:62,camouflage:38,fertility:76,metabolism:58,resistance:42,aggression:18}},
  {id:'predator',name:'中型捕食体',tier:3,role:'捕猎压制 / 低繁殖',color:'#ffb37c',traits:{speed:70,camouflage:34,fertility:32,metabolism:72,resistance:55,aggression:84}},
  {id:'scavenger',name:'杂食机会体',tier:2,role:'环境波动适应 / 泛化生存',color:'#7cc8ff',traits:{speed:48,camouflage:44,fertility:58,metabolism:46,resistance:60,aggression:36}},
  {id:'parasite',name:'寄生微型体',tier:1,role:'高扩散 / 高环境依赖',color:'#d7a9ff',traits:{speed:26,camouflage:68,fertility:82,metabolism:40,resistance:30,aggression:22}}
]

function clamp(n,min,max){return Math.max(min,Math.min(max,n))}
function mutateTrait(v,d){return clamp(v+d,1,99)}
function varyTraits(random,traits,amp=6){const out={...traits};for(const k of Object.keys(out)){out[k]=mutateTrait(out[k],Math.round((random()-.5)*amp*2))}return out}
function createAgents(r,count,x,y){return Array.from({length:count},()=>({x:x+(r()-.5)*80,y:y+(r()-.5)*80,vx:(r()-.5)*1.4,vy:(r()-.5)*1.4,age:Math.floor(r()*60),lifespan:220+Math.floor(r()*220),energy:60+r()*40,hunger:r()*20,reproductionCD:0}))}
function avgPos(agents){if(!agents.length)return{x:0,y:0};const s=agents.reduce((a,b)=>{a.x+=b.x;a.y+=b.y;return a},{x:0,y:0});return{x:s.x/agents.length,y:s.y/agents.length}}
function shiftColor(hex,delta){const h=hex.replace('#','');let n=parseInt(h,16);let r=(n>>16)&255,g=(n>>8)&255,b=n&255;r=clamp(r+delta,0,255);g=clamp(g+delta/2,0,255);b=clamp(b-delta/3,0,255);return '#'+[r,g,b].map(v=>Math.round(v).toString(16).padStart(2,'0')).join('')}
function idx(env,x,y){return y*env.fieldWidth+x}
function createField(env,fillFn){const arr=new Float32Array(env.fieldWidth*env.fieldHeight);for(let y=0;y<env.fieldHeight;y++){for(let x=0;x<env.fieldWidth;x++){arr[idx(env,x,y)]=fillFn(x,y)}}return arr}
function fieldPosToCell(env,x,y){const fx=clamp(Math.floor((x/900)*env.fieldWidth),0,env.fieldWidth-1);const fy=clamp(Math.floor((y/520)*env.fieldHeight),0,env.fieldHeight-1);return{fx,fy,i:idx(env,fx,fy)}}
function sampleField(env,x,y){const {i}=fieldPosToCell(env,x,y);return{flora:env.fields.flora[i],humidity:env.fields.humidity[i],temperature:env.fields.temperature[i],spores:env.fields.spores[i],carrion:env.fields.carrion[i],hazard:env.fields.hazard[i],complexity:env.fields.complexity[i]}}
function injectField(env,x,y,key,amount,radius=1){const {fx,fy}=fieldPosToCell(env,x,y);for(let yy=Math.max(0,fy-radius);yy<=Math.min(env.fieldHeight-1,fy+radius);yy++){for(let xx=Math.max(0,fx-radius);xx<=Math.min(env.fieldWidth-1,fx+radius);xx++){const d=Math.hypot(xx-fx,yy-fy);const weight=Math.max(0,1-d/(radius+0.001));env.fields[key][idx(env,xx,yy)]=clamp(env.fields[key][idx(env,xx,yy)]+amount*weight,0,160)}}}
function diffuseField(env,key,decay=0.985,diffusion=0.08,maxV=160){const src=env.fields[key];const out=new Float32Array(src.length);for(let y=0;y<env.fieldHeight;y++){for(let x=0;x<env.fieldWidth;x++){let sum=0,count=0;for(let yy=Math.max(0,y-1);yy<=Math.min(env.fieldHeight-1,y+1);yy++){for(let xx=Math.max(0,x-1);xx<=Math.min(env.fieldWidth-1,x+1);xx++){sum+=src[idx(env,xx,yy)];count++}}const i=idx(env,x,y);out[i]=clamp(src[i]*decay*(1-diffusion)+(sum/count)*diffusion,0,maxV)}}env.fields[key]=out}
function recomputeGlobalFromFields(env){const avg=a=>a.reduce((x,y)=>x+y,0)/a.length;env.resourcePools.flora=avg(env.fields.flora);env.resourcePools.carrion=avg(env.fields.carrion);env.resourcePools.spores=avg(env.fields.spores);env.humidity=avg(env.fields.humidity);env.temperature=avg(env.fields.temperature);env.hazard=avg(env.fields.hazard);env.complexity=avg(env.fields.complexity);env.resources=env.resourcePools.flora;env.mutationRate=clamp(0.04+env.hazard/260+Math.max(0,65-env.resources)/620+env.complexity/900,0.04,0.3);env.biomeLabel=biomeLabel(env)}
function biomeLabel(env){if(env.complexity>85&&env.resourcePools.flora>70)return '高复杂生态网';if(env.resourcePools.spores>45&&env.hazard>26)return '孢子沼泽';if(env.resourcePools.flora>95&&env.humidity>65)return '繁茂雨林';if(env.temperature>75&&env.humidity<25)return '荒漠热浪';if(env.hazard>30&&env.temperature>65)return '灼热裂谷';return '原始演替带'}
function createFields(env,random){const w=env.fieldWidth,h=env.fieldHeight;env.fields={flora:createField(env,(x,y)=>28+26*Math.sin((x/w)*Math.PI)+12*(1-y/h)+random()*8),humidity:createField(env,(x,y)=>35+40*(1-Math.abs(x/w-0.2))+random()*8),temperature:createField(env,(x,y)=>30+35*(x/w)+random()*6),spores:createField(env,(x,y)=>6+12*(x/w)*(1-y/h)+random()*4),carrion:createField(env,()=>random()*2),hazard:createField(env,(x,y)=>8+10*(x/w)+random()*4),complexity:createField(env,()=>random()*4)}}

export function getSpeciesPresets(){return speciesPresets}
export function createInitialWorld({seed,climateMode='temperate'}){const random=mulberry32(seed);const climateLabelMap={temperate:'温和',drought:'干旱',cold:'寒冷',volatile:'剧烈波动'};const environment={climateMode,climateLabel:climateLabelMap[climateMode],biomeLabel:'原始演替带',fieldWidth:18,fieldHeight:10,temperature:52,humidity:58,resources:80,hazard:12,complexity:2,mutationRate:0.08,resourcePools:{flora:55,carrion:3,spores:10}};createFields(environment,random);recomputeGlobalFromFields(environment);const initial=[speciesPresets[0],speciesPresets[1],speciesPresets[3]];const world={seed,random,tick:0,splitCounter:0,lastSplitTick:-999,environment,species:initial.map((preset,index)=>{const x=180+index*210;const y=160+index*85;const traits=varyTraits(random,preset.traits,8);const population=preset.tier===0?96:50-index*8;return {...JSON.parse(JSON.stringify(preset)),traits,lineage:preset.id,population,x,y,vx:(random()-.5)*2,vy:(random()-.5)*2,targetX:x,targetY:y,lastSplitTick:-999,splitProgress:0,extinct:false,agents:createAgents(random,clamp(Math.round(population/8),3,22),x,y)}}),history:[]};recordHistory(world);return world}
function recordHistory(world){world.history.push({tick:world.tick,species:world.species.map(s=>({id:s.id,name:s.name,population:s.population,color:s.color}))});if(world.history.length>80)world.history.shift()}
function find(world,id){return world.species.find(s=>s.id===id)}
function livingSpecies(world,predicate){return world.species.filter(s=>!s.extinct&&s.population>0&&predicate(s))}
function lifeMass(world,tier){return world.species.filter(s=>!s.extinct&&s.tier===tier).reduce((n,s)=>n+s.population,0)}

function updateEnvironment(world){const env=world.environment;const drift=(field,amount)=>{for(let i=0;i<field.length;i++)field[i]=clamp(field[i]+amount*(world.random()-.5),0,160)};drift(env.fields.temperature,env.climateMode==='volatile'?6:2);drift(env.fields.humidity,2);for(let y=0;y<env.fieldHeight;y++){for(let x=0;x<env.fieldWidth;x++){const i=idx(env,x,y);env.fields.temperature[i]=clamp(env.fields.temperature[i]+(x/env.fieldWidth-0.5)*1.2,0,160);env.fields.humidity[i]=clamp(env.fields.humidity[i]+(0.5-Math.abs(x/env.fieldWidth-0.2))*0.6,0,160);env.fields.flora[i]=clamp(env.fields.flora[i]+env.fields.humidity[i]/110-env.fields.temperature[i]/135-env.fields.hazard[i]/180+env.fields.complexity[i]/240,0,160);env.fields.spores[i]=clamp(env.fields.spores[i]*0.993+env.fields.carrion[i]*0.018+world.random()*0.22,0,160);env.fields.carrion[i]=clamp(env.fields.carrion[i]*0.986,0,160);env.fields.hazard[i]=clamp(env.fields.hazard[i]+env.fields.spores[i]*0.003-env.fields.complexity[i]*0.001,0,160);env.fields.complexity[i]=clamp(env.fields.complexity[i]*0.998+env.fields.flora[i]*0.003+env.fields.humidity[i]*0.002-env.fields.hazard[i]*0.002,0,160)}}diffuseField(env,'flora',0.995,0.10);diffuseField(env,'humidity',0.997,0.08);diffuseField(env,'temperature',0.998,0.05);diffuseField(env,'spores',0.993,0.16);diffuseField(env,'carrion',0.986,0.12);diffuseField(env,'hazard',0.994,0.10);diffuseField(env,'complexity',0.998,0.08);recomputeGlobalFromFields(env);return `Tick ${world.tick}: ${env.biomeLabel}｜气温 ${env.temperature.toFixed(0)}，湿度 ${env.humidity.toFixed(0)}，植物 ${env.resourcePools.flora.toFixed(0)}，残骸 ${env.resourcePools.carrion.toFixed(0)}，孢子 ${env.resourcePools.spores.toFixed(0)}，复杂度 ${env.complexity.toFixed(0)}`}
function applyEcologyFeedback(world){const env=world.environment;for(const s of world.species){if(s.extinct)continue;if(s.tier===0){injectField(env,s.x,s.y,'spores',0.18,1);injectField(env,s.x,s.y,'complexity',0.75,1);injectField(env,s.x,s.y,'flora',0.22,1)}else if(s.tier===1){injectField(env,s.x,s.y,'spores',0.42,1);injectField(env,s.x,s.y,'complexity',0.55,1);injectField(env,s.x,s.y,'hazard',0.09,1)}else if(s.tier===2){injectField(env,s.x,s.y,'flora',-0.85,1);injectField(env,s.x,s.y,'complexity',0.35,1)}else if(s.tier>=3){injectField(env,s.x,s.y,'carrion',0.30,1);injectField(env,s.x,s.y,'hazard',0.10,1);injectField(env,s.x,s.y,'complexity',0.25,1)}}diffuseField(env,'flora',0.996,0.08);diffuseField(env,'spores',0.993,0.14);diffuseField(env,'carrion',0.986,0.10);diffuseField(env,'hazard',0.994,0.08);diffuseField(env,'complexity',0.998,0.10);recomputeGlobalFromFields(env);return `生态反馈：低级生命 ${lifeMass(world,0)} / 初级寄生 ${lifeMass(world,1)} / 高级生命 ${lifeMass(world,2)+lifeMass(world,3)} / 复杂度 ${env.complexity.toFixed(0)}。`}
function applyStrategies(world,strategyProvider){const narratives=[];for(const species of world.species){if(species.extinct)continue;const strategy=strategyProvider.getStrategy({world,species});for(const k of Object.keys(strategy.mutationBias)){species.traits[k]=mutateTrait(species.traits[k],strategy.mutationBias[k])}narratives.push(`L${species.tier} ${species.name}：${strategy.narrative}`)}return narratives}
function applyMutation(world,species){const logs=[];if(world.random()<world.environment.mutationRate){const keys=['speed','camouflage','fertility','metabolism','resistance','aggression'];const key=keys[Math.floor(world.random()*keys.length)];const delta=world.random()<0.5?-2:2;species.traits[key]=mutateTrait(species.traits[key],delta);logs.push(`突变：L${species.tier} ${species.name} 的 ${key} ${delta>0?'增强':'减弱'}。`)}return logs}
function updateBoids(species,targetX,targetY){const agents=species.agents;const maxSpeed=Math.max(.5,species.traits.speed/30);for(let i=0;i<agents.length;i++){const a=agents[i];let alignX=0,alignY=0,cohX=0,cohY=0,sepX=0,sepY=0,count=0;for(let j=0;j<agents.length;j++){if(i===j)continue;const b=agents[j];const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy);if(d<80){alignX+=b.vx;alignY+=b.vy;cohX+=b.x;cohY+=b.y;count++;if(d<20){sepX-=dx/(d||1);sepY-=dy/(d||1)}}}if(count){alignX/=count;alignY/=count;cohX=cohX/count-a.x;cohY=cohY/count-a.y;a.vx+=alignX*.05+cohX*.003+sepX*.06;a.vy+=alignY*.05+cohY*.003+sepY*.06}a.vx+=(targetX-a.x)*.003;a.vy+=(targetY-a.y)*.003;const speed=Math.hypot(a.vx,a.vy)||1;if(speed>maxSpeed){a.vx=a.vx/speed*maxSpeed;a.vy=a.vy/speed*maxSpeed}a.x=clamp(a.x+a.vx,36,864);a.y=clamp(a.y+a.vy,36,484)}}
function markExtinct(species){species.population=0;species.extinct=true;species.agents=[];species.vx=0;species.vy=0}
function syncAgentCount(world,species){if(species.extinct||species.population<=0){markExtinct(species);return}const desired=clamp(Math.round(species.population/8),2,22);while(species.agents.length<desired){species.agents.push(...createAgents(world.random,1,species.x,species.y))}while(species.agents.length>desired){species.agents.pop()}}
function removeAgent(species,count){for(let i=0;i<count&&species.agents.length>0;i++){species.agents.splice(Math.floor(Math.random()*species.agents.length),1)}if(species.agents.length===0)markExtinct(species)}
function resolveGameInteractions(world){const logs=[];const env=world.environment;const predator=find(world,'predator');const grazer=find(world,'grazer');if(predator&&!predator.extinct&&grazer&&!grazer.extinct){const d=Math.hypot(predator.x-grazer.x,predator.y-grazer.y);const packBonus=Math.max(0,predator.agents.length-6)*0.12;const defense=Math.max(0,grazer.agents.length-8)*0.08;if(d<110&&predator.traits.aggression/100+packBonus>0.48-defense){const kills=clamp(Math.round(1+predator.traits.aggression/35+packBonus-defense),1,4);grazer.population=clamp(grazer.population-kills,0,240);removeAgent(grazer,kills);predator.population=clamp(predator.population+Math.max(1,Math.round(kills*.5)),0,240);injectField(env,predator.x,predator.y,'carrion',kills*4,1);logs.push(`围猎事件：L3 ${predator.name} 围猎 L2 ${grazer.name}，击杀 ${kills} 个体。`)}}return logs}
function chooseTarget(world,s){const env=world.environment;const predator=find(world,'predator');const grazer=find(world,'grazer');let best={score:-1e9,x:s.x,y:s.y};for(let gy=0;gy<env.fieldHeight;gy++){for(let gx=0;gx<env.fieldWidth;gx++){const i=idx(env,gx,gy);const x=(gx+0.5)/env.fieldWidth*900,y=(gy+0.5)/env.fieldHeight*520;const dist=Math.hypot(x-s.x,y-s.y);let score=-dist*0.03;if(s.tier===0)score+=env.fields.humidity[i]*0.7+env.fields.flora[i]*0.4-env.fields.hazard[i]*0.2;else if(s.tier===1)score+=env.fields.spores[i]*1.1+env.fields.complexity[i]*0.3;else if(s.lineage==='grazer')score+=env.fields.flora[i]*1.2-env.fields.spores[i]*0.4-env.fields.hazard[i]*0.5+(predator&&!predator.extinct?-Math.max(0,140-Math.hypot(x-predator.x,y-predator.y))*0.02:0);else if(s.lineage==='predator')score+=(grazer&&!grazer.extinct?-Math.hypot(x-grazer.x,y-grazer.y)*0.08:0)+env.fields.carrion[i]*0.2;else score+=env.fields.carrion[i]*0.8+env.fields.complexity[i]*0.3;if(score>best.score)best={score,x,y}}}return best}
function moveSpecies(world,s){if(s.extinct||s.population<=0||!s.agents||s.agents.length===0)return;const target=chooseTarget(world,s);s.targetX=clamp(target.x+(world.random()-.5)*16,60,840);s.targetY=clamp(target.y+(world.random()-.5)*16,60,460);updateBoids(s,s.targetX,s.targetY);const center=avgPos(s.agents);s.vx=(center.x-s.x)*.2;s.vy=(center.y-s.y)*.2;s.x=center.x;s.y=center.y}
function resolvePopulation(world){const env=world.environment;const predator=find(world,'predator');const logs=[];for(const species of world.species){if(species.extinct)continue;let deaths=0;for(const agent of species.agents){const local=sampleField(env,agent.x,agent.y);agent.age+=1;agent.hunger+=species.traits.metabolism/35;agent.energy-=species.traits.metabolism/48;agent.energy+=(local.flora+local.spores+local.carrion+local.complexity)/420;if(agent.age>agent.lifespan||agent.energy<=0||agent.hunger>130||local.hazard>110)deaths++}if(deaths>0){removeAgent(species,deaths);species.population=clamp(species.population-deaths,0,240);logs.push(`L${species.tier} ${species.name}：${deaths} 个体因老化、饥饿或局部环境恶化死亡。`)}const local=sampleField(env,species.x,species.y);let preferred=local.complexity*0.03;if(species.tier===0)preferred+=local.humidity*0.04+local.flora*0.03;else if(species.tier===1)preferred+=local.spores*0.08+local.complexity*0.04;else if(species.lineage==='grazer')preferred+=local.flora*0.08;else if(species.lineage==='predator')preferred+=local.carrion*0.06+1.2;else preferred+=local.carrion*0.06+local.flora*0.02;const crowdPenalty=Math.max(0,species.agents.length-10)*0.18;const fertilityGain=species.traits.fertility/28;const temperatureStress=Math.abs(local.temperature-50)/22;const droughtStress=local.humidity<25?(70-species.traits.resistance)/30:0;const hazardStress=local.hazard/28-species.traits.resistance/42;let predationStress=0;if((species.lineage!=='predator')&&predator&&!predator.extinct){const proximity=1/Math.max(1,Math.hypot(predator.x-species.x,predator.y-species.y)/120);predationStress=species.tier<2?0:proximity*(predator.population/260)-((species.traits.speed+species.traits.camouflage)/240)}species.population=clamp(Math.round(species.population+preferred+fertilityGain-temperatureStress-droughtStress-hazardStress-predationStress-crowdPenalty),0,240);logs.push(...applyMutation(world,species));syncAgentCount(world,species);moveSpecies(world,species)}recomputeGlobalFromFields(env);return logs}
function maybeSplitSpecies(world){const logs=[];const newborn=[];if(world.species.filter(s=>!s.extinct).length>=9)return logs;if(world.tick-world.lastSplitTick<24)return logs;for(const species of world.species){if(species.extinct)continue;if(world.species.filter(s=>!s.extinct).length+newborn.length>=9)break;const local=sampleField(world.environment,species.x,species.y);const divergence=Math.max(Math.abs(species.traits.speed-50),Math.abs(species.traits.camouflage-50),Math.abs(species.traits.resistance-50),Math.abs(species.traits.aggression-50));species.splitProgress=(species.splitProgress||0)+((species.population>120?1.2:0)+(local.hazard>24?1:0)+(local.flora<38?1:0)+(divergence>22?1:0))*0.65;if(species.population>140&&species.splitProgress>16&&world.tick-species.lastSplitTick>38){world.splitCounter+=1;const childId=`${species.id}_split_${world.splitCounter}`;const childName=`${species.name}·分支${world.splitCounter}`;const popShare=Math.max(12,Math.round(species.population*0.12));species.population=clamp(species.population-popShare,0,240);species.lastSplitTick=world.tick;species.splitProgress=0;world.lastSplitTick=world.tick;const childTraits=varyTraits(world.random,species.traits,10);const x=clamp(species.x+(world.random()-.5)*120,80,820),y=clamp(species.y+(world.random()-.5)*120,80,440);newborn.push({id:childId,lineage:species.lineage||species.id,name:childName,role:`${species.role} / 谱系分裂`,tier:species.tier,color:shiftColor(species.color,world.random()<0.5?-18:18),traits:childTraits,population:popShare,x,y,vx:(world.random()-.5)*2,vy:(world.random()-.5)*2,targetX:x,targetY:y,lastSplitTick:world.tick,splitProgress:0,extinct:false,agents:createAgents(world.random,clamp(Math.round(popShare/8),2,22),x,y)});logs.push(`物种分裂：L${species.tier} ${species.name} 分化出 ${childName}。`)}}if(newborn.length)world.species.push(...newborn);return logs}
function maybeEnvironmentSpawn(world){const logs=[];const env=world.environment;if(world.species.filter(s=>!s.extinct).length>=10)return logs;if(world.tick-world.lastSplitTick<16)return logs;for(let y=0;y<env.fieldHeight;y++){for(let x=0;x<env.fieldWidth;x++){const i=idx(env,x,y);let tier=null;if(env.fields.humidity[i]>45&&env.fields.flora[i]>28&&world.random()<0.003)tier=0;if(tier===null&&lifeMass(world,0)>80&&env.fields.spores[i]>28&&env.fields.complexity[i]>22&&world.random()<0.0025)tier=1;if(tier===null&&lifeMass(world,1)>45&&env.fields.flora[i]>50&&env.fields.complexity[i]>45&&world.random()<0.0018)tier=2;if(tier===null&&lifeMass(world,2)>70&&env.fields.carrion[i]>12&&env.fields.complexity[i]>60&&world.random()<0.0012)tier=3;if(tier===null)continue;world.splitCounter+=1;const px=(x+0.5)/env.fieldWidth*900,py=(y+0.5)/env.fieldHeight*520;const names=['原生膜质体','孢子游走体','环境适应体','高阶掠食体'];const colors=['#b7ffd8','#d7a9ff','#9df2b1','#ffb37c'];const base=[speciesPresets[0],speciesPresets[4]||speciesPresets[3],speciesPresets[1],speciesPresets[2]][tier]||speciesPresets[0];const traits=varyTraits(world.random,base.traits,18);world.species.push({id:`envborn_${world.splitCounter}`,lineage:tier===0?'microbe':tier===1?'parasite':tier===2?'grazer':'predator',name:`${names[tier]}${world.splitCounter}`,role:`环境孕育 / L${tier} 新生物`,tier,color:shiftColor(colors[tier],Math.round((world.random()-.5)*36)),traits,population:tier===0?42:22,x:px,y:py,vx:(world.random()-.5)*2,vy:(world.random()-.5)*2,targetX:px,targetY:py,lastSplitTick:world.tick,splitProgress:0,extinct:false,agents:createAgents(world.random,tier===0?8:4,px,py)});world.lastSplitTick=world.tick;logs.push(`环境孕育：局部环境先后演替，诞生 L${tier} ${names[tier]}${world.splitCounter}。`);return logs}}}return logs}
export function stepWorld(world,strategyProvider){world.tick+=1;const environmentNarrativeBase=updateEnvironment(world);const ecologyNarrative=applyEcologyFeedback(world);const speciesNarratives=[];speciesNarratives.push(...applyStrategies(world,strategyProvider));speciesNarratives.push(...resolveGameInteractions(world));speciesNarratives.push(...resolvePopulation(world));speciesNarratives.push(...maybeSplitSpecies(world));speciesNarratives.push(...maybeEnvironmentSpawn(world));recordHistory(world);return{environmentNarrative:`${environmentNarrativeBase}；${ecologyNarrative}`,speciesNarratives}}
